### ISSUE TITLE
是否可以根据读音来判断相似性

### ISSUE THREAD

**Issue by aonoa** [antlabs/strsim#7]
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**
语音识别时，模型识别成了同音字，或者s、sh；l、n；an、ang这种

**Comment by guonaihong** [comment]
strsim应该不会支持这个功能。可以找个拼音标注工具把文字转成拼音。再做相似度比较。

**Comment by aonoa** [comment]
> strsim应该不会支持这个功能。可以找个拼音标注工具把文字转成拼音。再做相似度比较。

好的，谢谢
